version: '3'

services: 
    db:
        image: postgres:12
        container_name: postgresql12
        volumes:
            - volume_db:/db
        restart: always
        env_file: .env
        ports: 
            - "5432:5432"
        networks: 
            - network_db
        
volumes: 
    volume_db:

networks: 
    network_db: